import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <ul className='nav' >
    <Link  href="/" ><li className="myul">Home</li></Link>
    <Link href="/"> <li className="myul">About</li></Link>
    <Link href=""><li className="myul">About</li></Link>
    <Link href=""> <li className="myul">Contact</li></Link>
    </ul>
        {children}</body>
    </html>
  )
  
}

